import type { Product } from "./types";

/** Catálogo inicial — el admin puede editar/reemplazar vía panel */
export const SEED_PRODUCTS: Product[] = [
  {
    id: "1",
    slug: "crop-tee-basica",
    name: "Crop Tee Básica",
    price: 65,
    description:
      "Tee corta de algodón suave. Ideal para armar outfits diarios con jeans o faldas.",
    category: "tops",
    segment: "adolescentes",
    gender: "mujer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Negro", "Blanco", "Arena"],
    image:
      "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=800&q=80",
    isNew: true,
    featured: true,
    active: true,
  },
  {
    id: "2",
    slug: "skinny-jeans",
    name: "Skinny Jeans",
    price: 150,
    description:
      "Jeans skinny de tiro medio con stretch. Corte que alarga la silueta.",
    category: "jeans",
    segment: "adultos",
    gender: "mujer",
    sizes: ["24", "26", "28", "30", "32"],
    colors: ["Azul oscuro", "Negro"],
    image:
      "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=800&q=80",
    featured: true,
    active: true,
  },
  {
    id: "3",
    slug: "set-deportivo-dos-piezas",
    name: "Set Deportivo 2 Piezas",
    price: 250,
    description:
      "Chaqueta y leggin a juego. Perfecto para gym o street look casual.",
    category: "sets",
    segment: "adolescentes",
    gender: "mujer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Gris"],
    image:
      "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?w=800&q=80",
    isNew: true,
    featured: true,
    active: true,
  },
  {
    id: "4",
    slug: "blusa-basica-manga-larga",
    name: "Blusa Básica Manga Larga",
    price: 75,
    description: "Blusa versátil de cuello redondo. Base ideal para capas.",
    category: "blusas",
    segment: "adultos",
    gender: "mujer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blanco", "Negro", "Rojo"],
    image:
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
    isNew: true,
    active: true,
  },
  {
    id: "5",
    slug: "vestido-midi-fluido",
    name: "Vestido Midi Fluido",
    price: 185,
    description:
      "Vestido midi con caída suave. De día a noche con un cambio de accesorio.",
    category: "vestidos",
    segment: "adultos",
    gender: "mujer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Negro", "Verde oliva"],
    image:
      "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800&q=80",
    featured: true,
    active: true,
  },
  {
    id: "6",
    slug: "short-denim-teen",
    name: "Short Denim Teen",
    price: 100,
    description: "Short de denim con dobladillo. Look fresco para el día a día.",
    category: "shorts",
    segment: "adolescentes",
    gender: "mujer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Azul claro", "Negro"],
    image:
      "https://images.unsplash.com/photo-1591195853828-11db59a44f6b?w=800&q=80",
    isNew: true,
    active: true,
  },
  {
    id: "7",
    slug: "polo-basica-nino",
    name: "Polo Básica Niño",
    price: 55,
    description: "Polo de algodón resistente para el colegio y fines de semana.",
    category: "tops",
    segment: "ninos",
    gender: "nino",
    sizes: ["4", "6", "8", "10", "12"],
    colors: ["Azul", "Blanco", "Rojo"],
    image:
      "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea?w=800&q=80",
    isNew: true,
    active: true,
  },
  {
    id: "8",
    slug: "vestido-nina-floral",
    name: "Vestido Niña Floral",
    price: 95,
    description: "Vestido ligero con estampado suave. Cómodo para jugar y salir.",
    category: "vestidos",
    segment: "ninos",
    gender: "nina",
    sizes: ["4", "6", "8", "10"],
    colors: ["Rosa", "Celeste"],
    image:
      "https://images.unsplash.com/photo-1518831959646-742c3a14ebf7?w=800&q=80",
    featured: true,
    active: true,
  },
  {
    id: "9",
    slug: "hoodie-unisex-teen",
    name: "Hoodie Unisex Teen",
    price: 175,
    description: "Hoodie oversized con capucha. Street style para todos.",
    category: "tops",
    segment: "adolescentes",
    gender: "unisex",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Gris melange"],
    image:
      "https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80",
    featured: true,
    active: true,
  },
  {
    id: "10",
    slug: "camisa-oxford-hombre",
    name: "Camisa Oxford Hombre",
    price: 140,
    description: "Oxford clásica de corte regular. Formal o casual con jeans.",
    category: "blusas",
    segment: "adultos",
    gender: "hombre",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blanco", "Celeste"],
    image:
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    active: true,
  },
  {
    id: "11",
    slug: "wide-leg-trousers",
    name: "Wide Leg Trousers",
    price: 110,
    description: "Pantalón wide leg con pretina elástica. Movimiento y estilo.",
    category: "jeans",
    segment: "adultos",
    gender: "mujer",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Beige"],
    image:
      "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1?w=800&q=80",
    isNew: true,
    active: true,
  },
  {
    id: "12",
    slug: "set-strapless-falda",
    name: "Set Strapless y Falda",
    price: 175,
    description: "Top strapless y falda a juego. Para salidas y eventos.",
    category: "sets",
    segment: "adolescentes",
    gender: "mujer",
    sizes: ["XS", "S", "M", "L"],
    colors: ["Negro", "Chocolate"],
    image:
      "https://images.unsplash.com/photo-1496747611176-843222e1e57c?w=800&q=80",
    isNew: true,
    featured: true,
    active: true,
  },
];
